# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'layerMorph' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	
  # Pods for layerMorph
  pod 'OneSignal'

  target 'layerMorphTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'layerMorphUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
